---
- name: Surveillance de la base de données
  hosts: database_servers
  tasks:
    - name: Installer l'agent de surveillance
      yum:
        name: monitoring_agent
        state: present
    - name: Configurer l'agent de surveillance
      template:
        src: monitoring_config.j2
        dest: /etc/monitoring/agent.conf
      notify: Redémarrer l'agent de surveillance
  handlers:
    - name: Redémarrer l'agent de surveillance
      service:
        name: monitoring_agent
        state: restarted
